 const eng={
    appname:"PakLoaders",
    getLuggage:"Get your luggage insured",
    luggageInsurance:"Luggage insurance is provided in case of loss or any damage of luggage",
    safe:"Safe and fast service",
    safty:"On time trip service is being provided with complete safety of luggage.",
    easyBook:"Easy to book a trip anytime all over Pakistan",
    language :"Language ",
    selectLanguage:"Please select a language",
    english:"English",
    urdu:"Urdu",
    // Login screen
    loginowner:"Login as Owner",
    logindriver:"Login as Driver",
    // Signup screen
    mobileNum:"Mobile Number",
    password:"Password",
    signUp:"Sign Up",
    fullName:"Full name",
    confirmPass:"Confirm Password",
    // verification
    veriCode:"Haven't received a code? Send again",
    veriButton:"Button(Verify) ",
    // verified screen
    veriSuccess:"You have successfully verified the account. ",
    ok:"Ok",
   //  Basic Screen info
   Welcome:"Welcome John Smith",
   completProfile:"Please complete your profile to proceed",
   fname:"First name ",
   lname:"Last name",
   dob:"Date of birth",
   SmNum:"Secondary mobile number",
   next:"Next ",
   cancel:"Cancel ",
   // Cnic details screen
   fimage:"front image of CNIC",
   bimg:"back image of cnic",
   cnic:"Cnic number",
   issueDate:"Issue date",
   expiryDate:"Expiry date",
   // Id confirmation
   vehicleInfo:"Vehicle Info",
   vehicleImg:"Add Vehicle image",
   vehicleReg:"Vehicle registration number",
   inssurnaceNum:"Insurance number",
   modelNum:"Model number",
   save:"Save",
   drivingLicence:"Driver License",
   licenceImg:"Front image of license",
   bLicenceImg:"Back image of license",
   licenceNum:"License number",
   // Ownership verification
   ownership:"Ownership verification",
   owner:"I am the owner of the vehicle",
   other:"Other",
   ownerVeriCode:"We will send you a verification code to the owner of the vehicle",
   fullName:"Full name",
   close:"Close",
   submit:"Submit",
   fpassword:"Forgot password",
   conf:"Confirm",
   resetPass:"Reset Password",
   newPass:"New Password",
   searchBar:"Search bar",
   newBids:"New bids",
   pickUp:"pick up",
   dropOff:"drop off",
   dateOfPickup:"date of pick up",
   viewDetail:"(View details) in bids home screen ",
   bidsReq:"Bids Requests",
   myEarning:"My Earnings",
   rating:"Rating",
   priceRange:"Price range ",
   distance:"Distance",
   apply:"Apply",
   close:"Close ",
   viewDetailScreen:"View Details Screen",
   bidsDetail:"Bids details",
   timing:"Timing",
   charges:"Charges",
   weight:"Weight",
   ignoreBtn:"Ignore btn",
   bidBtn:"Bid btn",
   amountmention:"Ammount Mentioned",
   bidsOnCustomCharges:"Bids on custom charges",
   bidAmount:"Your bid ammount",
   close:"Close",
   bidPlace:"Place bid",
   chats:"Chats",
   ongoing:"Ongoing",
   upcoming:"Upcoming",
   complete:"Completed",
   canceled:"Canceled",
   arrivalTime:"Arrival time",
   vehicleNum:"Vehicle No.",
   pickUpDate:"Pick up date",
   payment:"Payment",
   tripComplete:"Trip completed",
   endRide:"End ride",
   rideDetail:"Ride Detail",
   reciverNum:"Receiver name",


 }
   
const Urdu={
    appname:"پاک لوڈرز",
    getLuggage:"اپنے سامان کی بیمہ کروائیں۔",
    luggageInsurance:"سامان کے نقصان یا کسی نقصان کی صورت میں سامان کی انشورنس فراہم کی جاتی ہے",
    safe:"محفوظ اور تیز سروس",
    safty:"سامان کی مکمل حفاظت کے ساتھ آن ٹائم ٹرپ سروس فراہم کی جا رہی ہے",
    easyBook:"پورے پاکستان میں کسی بھی وقت ٹرپ بک کرنا آسان ہے",
    language :"زبان",
    selectLanguage:"براہ کرم ایک زبان منتخب کریں",
    english:"انگریزی",
    urdu:"اردو",
    // Login screen
    loginowner:"مالک کے طور پر لاگ ان کریں",
    logindriver:"ڈرائیور کے طور پر لاگ ان کریں",
    // Signup screen
    mobileNum:"موبائل نمبر",
    password:"پاس ورڈ",
    signUp:"سائن اپ",
    fullName:"پورا نام",
    confirmPass:"پاس ورڈ کی تصدیق کریں",
    // verification
    veriCode:"کوڈ موصول نہیں ہوا؟ دوبارہ بھیجو",
    veriButton:"تصدیق کریں ",
    // verified screen
    veriSuccess:"آپ نے کامیابی سے اکاؤنٹ کی تصدیق کر لی ہے ",
    ok:"ٹھیک ہے",
   //  Basic Screen info
   Welcome:"خوش آمدید جان سمتھ",
   completProfile:"براہ کرم آگے بڑھنے کے لیے اپناپروفائل مکمل کریں",
   fname:"پہلا نام ",
   lname:"آخری نام",
   dob:"پیدائش کی تاریخ",
   SmNum:"ثانوی موبائل نمبر",
   next:"اگلے",
   cancel:"منسوخ ",
   // Cnic details screen
   fimage:"کی سامنے کی تصویر CNIC",
   bimg:"کی پچھلی تصویر CNIC",
   cnic:"نمبر Cnic",
   issueDate:"Issue date",
   expiryDate:"Expiry date",
   // Id confirmation
   vehicleInfo:"Vehicle Info",
   vehicleImg:"Add Vehicle image",
   vehicleReg:"Vehicle registration number",
   inssurnaceNum:"Insurance number",
   modelNum:"Model number",
   save:"Save",
   drivingLicence:"Driver License",
   licenceImg:"Front image of license",
   bLicenceImg:"Back image of license",
   licenceNum:"License number",
   // Ownership verification
   ownership:"Ownership verification",
   owner:"I am the owner of the vehicle",
   other:"Other",
   ownerVeriCode:"We will send you a verification code to the owner of the vehicle",
   fullName:"Full name",
   close:"Close",
   submit:"Submit",
   fpassword:"Forgot password",
   conf:"Confirm",
   resetPass:"Reset Password",
   newPass:"New Password",
   searchBar:"Search bar",
   newBids:"New bids",
   pickUp:"pick up",
   dropOff:"drop off",
   dateOfPickup:"date of pick up",
   viewDetail:"(View details) in bids home screen ",
   bidsReq:"Bids Requests",
   myEarning:"My Earnings",
   rating:"Rating",
   priceRange:"Price range ",
   distance:"Distance",
   apply:"Apply",
   close:"Close ",
   viewDetailScreen:"View Details Screen",
   bidsDetail:"Bids details",
   timing:"Timing",
   charges:"Charges",
   weight:"Weight",
   ignoreBtn:"Ignore btn",
   bidBtn:"Bid btn",
   amountmention:"Ammount Mentioned",
   bidsOnCustomCharges:"Bids on custom charges",
   bidAmount:"Your bid ammount",
   close:"Close",
   bidPlace:"Place bid",
   chats:"Chats",
   ongoing:"Ongoing",
   upcoming:"Upcoming",
   complete:"Completed",
   canceled:"Canceled",
   arrivalTime:"Arrival time",
   vehicleNum:"Vehicle No.",
   pickUpDate:"Pick up date",
   payment:"Payment",
   tripComplete:"Trip completed",
   endRide:"End ride",
   rideDetail:"Ride Detail",
   reciverNum:"Receiver name",
   

 }

export {eng,Urdu};