 const eng={
    appname:"PakLoaders",
    getLuggage:"Get your luggage insured",
    luggageInsurance:"Luggage insurance is provided in case of loss or any damage of luggage",
    safe:"Safe and fast service",
    safty:"On time trip service is being provided with complete safety of luggage.",
    easyBook:"Easy to book a trip anytime all over Pakistan",
    language :"Language ",
    selectLanguage:"Please select a language",
    english:"English",
    urdu:"Urdu",
    // Login screen
    loginowner:"Login as Owner",
    logindriver:"Login as Driver",
    // Signup screen
    mobileNum:"Mobile Number",
    password:"Password",
    signUp:"Sign Up",
    fullName:"Full name",
    confirmPass:"Confirm Password",
    // verification
    veriCode:"Haven't received a code? Send again",
    veriButton:"Button(Verify) ",
    // verified screen
    veriSuccess:"You have successfully verified the account. ",
    ok:"Ok",
   //  Basic Screen info
   Welcome:"Welcome John Smith",
   completProfile:"Please complete your profile to proceed",
   fname:"First name ",
   lname:"Last name",
   dob:"Date of birth",
   SmNum:"Secondary mobile number",
   next:"Next ",
   cancel:"Cancel ",
   // Cnic details screen
   fimage:"front image of CNIC",
   bimg:"back image of cnic",
   cnic:"Cnic number",
   issueDate:"Issue date",
   expiryDate:"Expiry date",
   // Id confirmation
   vehicleInfo:"Vehicle Info",
   vehicleImg:"Add Vehicle image",
   vehicleReg:"Vehicle registration number",
   inssurnaceNum:"Insurance number",
   modelNum:"Model number",
   save:"Save",
   drivingLicence:"Driver License",
   licenceImg:"Front image of license",
   bLicenceImg:"Back image of license",
   licenceNum:"License number",
   // Ownership verification
   ownership:"Ownership verification",
   owner:"I am the owner of the vehicle",
   other:"Other",
   ownerVeriCode:"We will send you a verification code to the owner of the vehicle",
   fullName:"Full name",
   close:"Close",
   submit:"Submit",
   fpassword:"Forgot password",
   conf:"Confirm",
   resetPass:"Reset Password",
   newPass:"New Password",
   searchBar:"Search bar",
   newBids:"New bids",
   pickUp:"pick up",
   dropOff:"drop off",
   dateOfPickup:"date of pick up",
   viewDetail:"(View details) in bids home screen ",
   bidsReq:"Bids Requests",
   myEarning:"My Earnings",
   rating:"Rating",
   priceRange:"Price range ",
   distance:"Distance",
   apply:"Apply",
   close:"Close ",
   viewDetailScreen:"View Details Screen",
   bidsDetail:"Bids details",
   timing:"Timing",
   charges:"Charges",
   weight:"Weight",
   ignoreBtn:"Ignore btn",
   bidBtn:"Bid btn",
   amountmention:"Ammount Mentioned",
   bidsOnCustomCharges:"Bids on custom charges",
   bidAmount:"Your bid ammount",
   close:"Close",
   bidPlace:"Place bid",
   chats:"Chats",
   ongoing:"Ongoing",
   upcoming:"Upcoming",
   complete:"Completed",
   canceled:"Canceled",
   arrivalTime:"Arrival time",
   vehicleNum:"Vehicle No.",
   pickUpDate:"Pick up date",
   payment:"Payment",
   tripComplete:"Trip completed",
   endRide:"End ride",
   rideDetail:"Ride Detail",
   reciverNum:"Receiver name",
   amountPayed:"Amount payed",
   experience:"Please share your experience with us",
   feedback:"Wrie your feedback",
   essentialFeatures:"Essential 4Features",
   unlimitedLoad:"Unlimited load views",
   annualPlan:"Annual plan",
   creditCard:"Credit / Debit Card",
   easypaisa:"Easypaisa",
   jazzcash:"Jazzcash",
   bankAccount:"Bank Account",
   payNow:"Pay Now",
   cardHolder:"Card holder name",
   cardNumber:"Card number ",
   monthYearCv:"Month, year, cvv",
   jazzcashNumber:"Pay with your jazzcash account. Enter the jazzcash registered mobile number",
    jazzcshMobileNumber:"Jazzcash mobile number",
    Mpin:"Mpin",
    tripsCompleted:"Trips completed",
    tripsInprogress:"Trips inprogress ",
   //  Custom Drawer
   home:"Home",
    editPost:"Edit Post",
    packages:"Packages",
    insuredLuggage:"Insured Luggage",
    myRides:"My Rides",
    myPost:"My Post",
    chat:"Chat",
    payment:"Payment",
    share:"Share",
    contactUs:"Contact Us",
    rate:"Rate",
    logOut:"Log Out",
   //  Custom Drawer
    addPost:"Add Post",
    createPost:"Create Post"
 }
   
const Urdu={
    appname:"پاک لوڈرز",
    getLuggage:"اپنے سامان کی بیمہ کروائیں۔",
    luggageInsurance:"سامان کے نقصان یا کسی نقصان کی صورت میں سامان کی انشورنس فراہم کی جاتی ہے",
    safe:"محفوظ اور تیز سروس",
    safty:"سامان کی مکمل حفاظت کے ساتھ آن ٹائم ٹرپ سروس فراہم کی جا رہی ہے",
    easyBook:"پورے پاکستان میں کسی بھی وقت ٹرپ بک کرنا آسان ہے",
    language :"زبان",
    selectLanguage:"براہ کرم ایک زبان منتخب کریں",
    english:"انگریزی",
    urdu:"اردو",
    // Login screen
    loginowner:"مالک کے طور پر لاگ ان کریں",
    logindriver:"ڈرائیور کے طور پر لاگ ان کریں",
    // Signup screen
    mobileNum:"موبائل نمبر",
    password:"پاس ورڈ",
    signUp:"سائن اپ",
    fullName:"پورا نام",
    confirmPass:"پاس ورڈ کی تصدیق کریں",
    // verification
    veriCode:"کوڈ موصول نہیں ہوا؟ دوبارہ بھیجو",
    veriButton:"تصدیق کریں ",
    // verified screen
    veriSuccess:"آپ نے کامیابی سے اکاؤنٹ کی تصدیق کر لی ہے ",
    ok:"ٹھیک ہے",
   //  Basic Screen info
   Welcome:"خوش آمدید جان سمتھ",
   completProfile:"براہ کرم آگے بڑھنے کے لیے اپناپروفائل مکمل کریں",
   fname:"پہلا نام ",
   lname:"آخری نام",
   dob:"پیدائش کی تاریخ",
   SmNum:"ثانوی موبائل نمبر",
   next:"اگلے",
   cancel:"منسوخ ",
   // Cnic details screen
   fimage:"کی سامنے کی تصویر CNIC",
   bimg:"کی پچھلی تصویر CNIC",
   cnic:"نمبر Cnic",
   issueDate:"تاریخ اجراء",
   expiryDate:"خاتمے کی تاریخ",
   // Id confirmation
   vehicleInfo:"گاڑی کی معلومات",
   vehicleImg:"گاڑی کی تصویر شامل کریں",
   vehicleReg:"گاڑی کا رجسٹریشن نمبر",
   inssurnaceNum:"انشورنس نمبر",
   modelNum:"ماڈل نمبر",
   save:"محفوظ کریں",
   drivingLicence:"ڈرائیور لائسنس",
   licenceImg:"لائسنس کی سامنے کی تصویر",
   bLicenceImg:"لائسنس کی پچھلی تصویر",
   licenceNum:"لائسنس نمبر",
   // Ownership verification
   ownership:"ملکیت کی تصدیق",
   owner:"میں گاڑی کا مالک ہوں",
   other:"دوسرے",
   ownerVeriCode:"ہم آپ کو گاڑی کے مالک کو ایک تصدیقی کوڈ بھیجیں گے",
   fullName:"پورا نام",
   close:"بند کریں",
   submit:"جمع کرائیں",
   fpassword:"پاسورڈ بھول گے",
   conf:"تصدیق کریں",
   resetPass:"پاس ورڈ ری سیٹ",
   newPass:"نیا پاس ورڈ",
   searchBar:"تلاش کریں",
   newBids:"نئی بولیاں",
   pickUp:"اٹھاؤ",
   dropOff:"چھوڑ",
   dateOfPickup:"لینے کی تاریخ",
   viewDetail:"تفصیل دیکھیں",
   bidsReq:"بولی کی تفصیلات",
   myEarning:"میری کمائی",
   rating:"درجہ بندی",
   priceRange:"قیمت کی حد",
   distance:"فاصلہ",
   apply:"درخواست دیں",
   close:"بند کریں",
   viewDetailScreen:"تفصیل دیکھیں",
   bidsDetail:"بولی کی تفصیلات",
   timing:"ٹائمنگ",
   charges:"چارجز",
   weight:"وزن",
   ignoreBtn:"نظر انداز",
   bidBtn:"بول",
   amountmention:"ذکر شدہ رقم",
   bidsOnCustomCharges:"اپنی مرضی کے چارجز پر بولیاں",
   bidAmount:"]آپ کی بولی کی رقم",
   close:"بند کریں",
   bidPlace:"جگہ کی بولی",
   chats:"چیٹس",
   ongoing:"جاری ہے",
   upcoming:"آنے والا",
   complete:"مکمل",
   canceled:"منسوخ",
   arrivalTime:"آمد کے وقت",
   vehicleNum:"گاڑی نمبر",
   pickUpDate:"تاریخ اٹھاو",
   payment:"ادائیگی",
   tripComplete:"سفر مکمل",
   endRide:"سواری ختم",
   rideDetail:"سواری کی تفصیلات",
   reciverNum:"وصول کنندہ کا نام",
    //  Custom Drawer
    home:"ہوم",
    editPost:"پوسٹ میں ترمیم کریں",
    packages:"پیکجز",
    insuredLuggage:"بیمہ شدہ سامان",
    myRides:"میری سواریاں",
    myPost:"میری پوسٹ",
    chat:"گپ شپ",
    payment:"ادائیگی",
    share:"بانٹیں",
    contactUs:"ہم سے رابطہ کریں",
    rate:"شرح",
    logOut:"لاگ آوٹ",
   //  Custom Drawer
    addPost:"پوسٹ شامل کریں",
    createPost:"پوسٹ بنائیں"
 }

export {eng,Urdu};