export const LOAD_DEVICE_TOKENS_INTO_REDUCER =
  'GRANNY/LOAD_DEVICE_TOKENS_INTO_REDUCER';
export type LOAD_DEVICE_TOKENS_INTO_REDUCER = typeof LOAD_DEVICE_TOKENS_INTO_REDUCER;
export interface ILoadTokensRequest {}

export const LOAD_ACCOUNT_INTO_REDUCER = 'GRANNY/LOAD_ACCOUNT_INTO_REDUCER';
export type LOAD_ACCOUNT_INTO_REDUCER = typeof LOAD_ACCOUNT_INTO_REDUCER;
export interface ILoadAccountrRequest {}
